### ISSUE TITLE
Many errors with mysql 5.7.12

### ISSUE THREAD

**Issue by arm2arm** [cea-hpc/robinhood#18] opened 2016-04-28 15:56 UTC
I have following setup:
mysql 5.7.12 community edition
robinhood 2.5.5(or 3.0.0 alpha )
The command scan throws many errors:
**robinhood -f llust  -L stdout --scan --once**

2016/04/28 17:48:53 [2182/3] ListMgr | DB query failed in ListMgr_BatchInsert line 342: code=7: 
2016/04/28 17:48:53 [2182/3] EntryProc | Error 7 performing batch database operation: request error.
2016/04/28 17:48:53 [2182/8] ListMgr | Unhandled error 3020: default conversion to DB_REQUEST_FAILED
2016/04/28 17:48:53 [2182/8] ListMgr | Error 7 executing query 'INSERT INTO ENTRIES(id,owner,gr_name,size,b....
.....

What could  be the reason?
thanks,
Arman

**Comment by tl-cea** [comment] 2016-05-09 19:25
> Unhandled error 3020
"grep" in mysql headers (/usr/include/mysql/*) often helps to find the cause

**Comment by tl-cea** [comment] 2016-09-13 20:32
rc2 will be tested on mysql 5.7. We addressed all detected issues on this version.

**Comment by tl-cea** [comment] 2016-09-16 14:48
Just now be fixed with just released 3.0 (final).

**Closed by tl-cea** 2016-09-16 14:48 UTC
